(()=>{
  const RESULT_KEY='epsTopikReleaseResultV1';
  const state={questions:[],index:0,answers:{},plays:{},seconds:50*60,timer:null,submitted:false};
  const $=id=>document.getElementById(id);
  const el={sectionTitle:$('sectionTitle'),answeredCount:$('answeredCount'),timer:$('timer'),readingNav:$('readingNav'),listeningNav:$('listeningNav'),questionNumber:$('questionNumber'),sectionBadge:$('sectionBadge'),progressLabel:$('progressLabel'),progressBar:$('progressBar'),prompt:$('prompt'),mediaWrap:$('mediaWrap'),audioWrap:$('audioWrap'),audioButton:$('audioButton'),audioCount:$('audioCount'),stem:$('stem'),options:$('options'),prev:$('prevButton'),next:$('nextButton'),modal:$('submitModal'),submitStatus:$('submitStatus'),cancelSubmit:$('cancelSubmit'),confirmSubmit:$('confirmSubmit')};
  async function load(){const[r,l]=await Promise.all([fetch('data/reading.json',{cache:'no-store'}),fetch('data/listening.json',{cache:'no-store'})]);if(!r.ok||!l.ok)throw new Error();state.questions=[...(await r.json()),...(await l.json())];render();startTimer()}
  const current=()=>state.questions[state.index];
  const label=q=>q.section==='reading'?'읽기 · Reading':'듣기 · Listening';
  function render(){const q=current();EPSTTS.cancel();el.sectionTitle.textContent=label(q);el.questionNumber.textContent=q.id;el.sectionBadge.textContent=label(q);el.progressLabel.textContent=`${state.index+1} / ${state.questions.length}`;el.progressBar.style.width=`${((state.index+1)/state.questions.length)*100}%`;el.prompt.textContent=q.prompt||'';renderMedia(q);renderAudio(q);renderStem(q);renderOptions(q);renderNav();el.prev.disabled=state.index===0;el.next.textContent=state.index===state.questions.length-1?'제출 · Submit':'다음 · Next';el.answeredCount.textContent=`답변 · Answered ${Object.keys(state.answers).length} / ${state.questions.length}`}
  function renderMedia(q){el.mediaWrap.innerHTML='';if(!q.media)return el.mediaWrap.classList.add('hidden');const img=document.createElement('img');img.src=q.media;img.alt='';el.mediaWrap.appendChild(img);el.mediaWrap.classList.remove('hidden')}
  function renderStem(q){if(!q.stem){el.stem.textContent='';return el.stem.classList.add('hidden')}el.stem.textContent=q.stem;el.stem.classList.remove('hidden')}
  const maxPlays=q=>Number(q.audio?.maxPlays??2);
  function renderAudio(q){if(q.section!=='listening'||!q.audio)return el.audioWrap.classList.add('hidden');el.audioWrap.classList.remove('hidden');const used=state.plays[q.id]||0,remain=Math.max(maxPlays(q)-used,0);el.audioCount.textContent=`${remain} / ${maxPlays(q)}`;el.audioButton.disabled=remain<=0;el.audioButton.querySelector('span:last-child').textContent='듣기 · Play Audio'}
  function renderOptions(q){el.options.innerHTML='';el.options.className='options-grid';const images=q.options.every(o=>typeof o==='object'&&o.image),numeric=['audio_only_options','picture_audio_options'].includes(q.type);if(images)el.options.classList.add('image-options');if(numeric)el.options.classList.add('numeric-only');q.options.forEach((o,i)=>{const b=document.createElement('button');b.type='button';if(images){b.className='image-option';const img=document.createElement('img');img.src=o.image;img.alt='';const idx=document.createElement('span');idx.className='option-index';idx.textContent=i+1;b.append(img,idx)}else{b.className='option-btn';const idx=document.createElement('span');idx.className='option-index';idx.textContent=i+1;const t=document.createElement('span');t.className='option-label';t.textContent=typeof o==='string'?o:'';b.append(idx,t)}if(state.answers[q.id]===i)b.classList.add('selected');b.addEventListener('click',()=>{state.answers[q.id]=i;render()});el.options.appendChild(b)})}
  function renderNav(){el.readingNav.innerHTML='';el.listeningNav.innerHTML='';state.questions.forEach((q,i)=>{const b=document.createElement('button');b.type='button';b.className='nav-btn';b.textContent=q.id;if(state.answers[q.id]!==undefined)b.classList.add('answered');if(i===state.index)b.classList.add('current');b.onclick=()=>{state.index=i;render()};(q.section==='reading'?el.readingNav:el.listeningNav).appendChild(b)})}
  function play(){const q=current();if(!q.audio)return;const used=state.plays[q.id]||0;if(used>=maxPlays(q))return;state.plays[q.id]=used+1;renderAudio(q);el.audioButton.disabled=true;el.audioButton.querySelector('span:last-child').textContent='재생 중 · Playing';EPSTTS.speak(q.audio,{onEnd:()=>renderAudio(q),onError:()=>renderAudio(q)})}
  function next(){EPSTTS.cancel();if(state.index<state.questions.length-1){state.index++;render()}else openSubmit()}
  function prev(){EPSTTS.cancel();if(state.index>0){state.index--;render()}}
  function openSubmit(){const answered=Object.keys(state.answers).length;el.submitStatus.textContent=`${state.questions.length}문항 중 ${answered}문항에 답했습니다. · Answered ${answered} of ${state.questions.length} questions.`;el.modal.classList.remove('hidden')}
  function closeSubmit(){el.modal.classList.add('hidden')}
  function submit(){if(state.submitted)return;state.submitted=true;clearInterval(state.timer);EPSTTS.cancel();let r=0,l=0;state.questions.forEach(q=>{if(state.answers[q.id]===q.answer){if(q.section==='reading')r++;else l++}});const correct=r+l;localStorage.setItem(RESULT_KEY,JSON.stringify({total:state.questions.length,readingCorrect:r,listeningCorrect:l,correct,wrong:state.questions.length-correct,percentage:Math.round(correct/state.questions.length*100),answered:Object.keys(state.answers).length}));location.href='result.html'}
  function startTimer(){tick();state.timer=setInterval(()=>{state.seconds--;tick();if(state.seconds<=0){clearInterval(state.timer);submit()}},1000)}
  function tick(){const s=Math.max(0,state.seconds),m=Math.floor(s/60),r=s%60;el.timer.textContent=`${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`}
  el.audioButton.onclick=play;el.next.onclick=next;el.prev.onclick=prev;el.cancelSubmit.onclick=closeSubmit;el.confirmSubmit.onclick=submit;window.addEventListener('beforeunload',()=>EPSTTS.cancel());
  load().catch(()=>{el.prompt.textContent='문항을 불러올 수 없습니다.'});
})();
